-- Table for storing JWT refresh tokens
CREATE TABLE TNDR_REFRESH_TOKENS (
    TOKEN_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20 CHAR) NOT NULL,
    TOKEN VARCHAR2(500 CHAR) NOT NULL UNIQUE,
    EXPIRATION_DATE DATE NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
    IS_REVOKED NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_REFRESH_TOKENS_USER 
        FOREIGN KEY (USER_ID) 
        REFERENCES TNDR_USER(USER_ID)
);

-- Index for better performance
CREATE INDEX IDX_REFRESH_TOKENS_USER_ID ON TNDR_REFRESH_TOKENS(USER_ID);
CREATE INDEX IDX_REFRESH_TOKENS_TOKEN ON TNDR_REFRESH_TOKENS(TOKEN);
CREATE INDEX IDX_REFRESH_TOKENS_EXPIRATION ON TNDR_REFRESH_TOKENS(EXPIRATION_DATE);

-- Sequence for TOKEN_ID
CREATE SEQUENCE SEQ_REFRESH_TOKENS_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger to auto-increment TOKEN_ID
CREATE OR REPLACE TRIGGER TRG_REFRESH_TOKENS_ID
    BEFORE INSERT ON TNDR_REFRESH_TOKENS
    FOR EACH ROW
BEGIN
    SELECT SEQ_REFRESH_TOKENS_ID.NEXTVAL INTO :NEW.TOKEN_ID FROM DUAL;
END;
/

-- Table for storing JWT access tokens (optional, for token blacklisting)
CREATE TABLE TNDR_JWT_TOKENS (
    TOKEN_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20 CHAR) NOT NULL,
    TOKEN VARCHAR2(500 CHAR) NOT NULL UNIQUE,
    EXPIRATION_DATE DATE NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
    IS_BLACKLISTED NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_JWT_TOKENS_USER 
        FOREIGN KEY (USER_ID) 
        REFERENCES TNDR_USER(USER_ID)
);

-- Index for better performance
CREATE INDEX IDX_JWT_TOKENS_USER_ID ON TNDR_JWT_TOKENS(USER_ID);
CREATE INDEX IDX_JWT_TOKENS_TOKEN ON TNDR_JWT_TOKENS(TOKEN);
CREATE INDEX IDX_JWT_TOKENS_EXPIRATION ON TNDR_JWT_TOKENS(EXPIRATION_DATE);

-- Sequence for TOKEN_ID
CREATE SEQUENCE SEQ_JWT_TOKENS_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger to auto-increment TOKEN_ID
CREATE OR REPLACE TRIGGER TRG_JWT_TOKENS_ID
    BEFORE INSERT ON TNDR_JWT_TOKENS
    FOR EACH ROW
BEGIN
    SELECT SEQ_JWT_TOKENS_ID.NEXTVAL INTO :NEW.TOKEN_ID FROM DUAL;
END;
/